# Site settings
name: eva's bolg
email: 515365161@qq.com
author: zhang xin
url: https://pimozid.github.io/
resume_site: 
github: https://github.com/pimozid/pimozid.github.io
baseurl: ""
description: 
meta_description: 章鑫;个人博客;
motto: It's our wits that make us men.
banner: jkljlkjj。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

