# Permalinks
permalink:        /post/:title.html

# Setup
url:              //pimozid.github.io
img_url:          ''

# Set to '' in case of hosting on `https://<your-github-name>.github.io`
baseurl:          ''

title:            'AAA'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:        >
关于[代码](/code)、[宇宙](/read)、[生活](/life)和[一切](/)。


# Google Analytics tracking ID
analytics:        'UA-32028925-2'

# Fallback image and color if not overwritten for tag or post
image:            /public/images/mountains.jpg
color:            '#dc322f'

author:
  name:           'asd'
  email:          515365161@qq.com
  github:         pimozid
  linkedin:       ''
  weibo:          pimozid
  facebook:       ''
  photo:          /public/images/cat.jpg


  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    我是，热爱，喜欢。我的微博是 []()


compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]

sass:
  sass_dir:       /public/css
  style:          compressed
